"""AI and local heuristic threat analysis blueprint."""
from flask import Blueprint, request, jsonify
from app.utils.decorators import require_login, require_permission
from app.models.setting import Setting

analysis_bp = Blueprint("analysis", __name__)


def build_local_ai_remediation(data):
    """Fallback local threat remediation guidance in TR and EN."""
    threat_type = str(data.get("type") or data.get("category") or "UNKNOWN")
    severity = str(data.get("severity") or "LOW").upper()
    action = str(data.get("action") or "ALERT").upper()
    source = str(data.get("source") or data.get("src_ip") or "-")
    destination = str(data.get("destination") or data.get("dst_ip") or "-")

    remediations_tr = {
        "SQL_INJECTION": "Parametreli sorgular kullanın ve kullanıcı girdisini doğrudan sorguya eklemeyin.",
        "XSS_ATTACK": "Çıktı kodlaması (output encoding) ve sıkı bir Content Security Policy (CSP) uygulayın.",
        "PATH_TRAVERSAL": "Dosya yollarını normalize edin ve taban dizin dışına erişimi engelleyin.",
        "COMMAND_INJECTION": "Kabuk (shell) fonksiyonlarını kullanıcı girdisiyle doğrudan çağırmaktan kaçının.",
    }
    remediations_en = {
        "SQL_INJECTION": "Enforce parameterized queries (prepared statements) and avoid raw concatenation.",
        "XSS_ATTACK": "Implement strict context-aware output encoding and Content Security Policy (CSP).",
        "PATH_TRAVERSAL": "Normalize file paths and validate inputs against a strict allowed directory whitelist.",
        "COMMAND_INJECTION": "Avoid shell execution functions with user-supplied arguments.",
    }

    rem_tr = remediations_tr.get(threat_type, "Tehdit kaynağını inceleyin ve gerekirse IP adresini engelleyin.")
    rem_en = remediations_en.get(threat_type, "Inspect the threat origin and apply dynamic IP blocking if needed.")

    return {
        "tr": {
            "title": f"{threat_type} Güvenlik Olayı İncelemesi",
            "summary": f"{source} adresinden gelen {severity} seviyesinde {threat_type} şüpheli hareketi tespit edildi.",
            "risk": f"{severity} risk seviyesi. Saldırgan sistem zafiyetlerini araştırmış olabilir.",
            "evidence": f"Kaynak: {source} -> Hedef: {destination} | Karar: {action}",
            "immediate_actions": [f"Kaynak IP {source} adresini inceleyin.", "Şüpheli bağlantıyı sonlandırın."],
            "containment": "Ağ segmentasyonu ve aktif IP engellemesi uygulayın.",
            "remediation": [rem_tr],
            "monitoring": "İlgili IP ve alt ağdan gelen trafiği izlemeye alın.",
            "notes": "vGuard yerel kural motoru tarafından otomatik oluşturulmuştur.",
        },
        "en": {
            "title": f"{threat_type} Security Event Analysis",
            "summary": f"Detected {severity} severity {threat_type} suspicious pattern from {source}.",
            "risk": f"{severity} risk level. Originator may be probing for vulnerabilities.",
            "evidence": f"Source: {source} -> Dest: {destination} | Verdict: {action}",
            "immediate_actions": [f"Review source IP {source} activity.", "Terminate unauthorized sessions."],
            "containment": "Enforce network segmentation and ban source IP if persistent.",
            "remediation": [rem_en],
            "monitoring": "Monitor logs for repeated reconnaissance or brute force attempts.",
            "notes": "Generated by vGuard heuristic engine.",
        },
        "meta": {
            "source": source,
            "destination": destination,
            "event_type": threat_type,
            "severity": severity,
            "action": action,
            "mode": "local_fallback",
        },
    }


@analysis_bp.route("/api/analyze", methods=["POST"])
@require_login
@require_permission("use_ai")
def analyze_threat():
    """Analyze a threat event using Gemini AI or local heuristic fallback."""
    data = request.get_json(silent=True) or {}
    fallback = build_local_ai_remediation(data)

    api_key = Setting.get("gemini_api_key", "")
    if not api_key:
        return jsonify({"analysis": fallback}), 200

    try:
        import google.generativeai as genai
        genai.configure(api_key=api_key)
        # If API key configured, attempt model call with quick timeout
        model = genai.GenerativeModel("gemini-1.5-flash")
        prompt = f"Analyze threat: {data.get('type')} from {data.get('source')}. Return brief SOC advice."
        res = model.generate_content(prompt)
        if res and res.text:
            fallback["en"]["summary"] = res.text[:500]
            fallback["meta"]["mode"] = "gemini_pro"
    except Exception:
        fallback["meta"]["mode"] = "local_fallback"

    return jsonify({"analysis": fallback}), 200
